version: "3.9"

services:
    database:
        env_file:
            - ./.env
        image: postgres
        container_name: to-do
        ports:
            - 5432:${POSTGRES_PORT}
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        volumes:
            - pgdata:/data/postgres

volumes:
    pgdata:
        driver: local
